# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "setuptools"
        versions: ["*"]
      - dependency-name: "pytest"
        versions: ["*"]
      - dependency-name: "pytest-cov"
        versions: ["*"]
      - dependency-name: "pytest-pycharm"
        versions: ["*"]
      - dependency-name: "python-dotenv"
        versions: ["*"]
      - dependency-name: "typing_extensions"
        versions: ["*"]
      - dependency-name: "vulture"
        versions: ["*"]
      - dependency-name: "bandit"
        versions: ["*"]
      - dependency-name: "whispers"
        versions: ["*"]
