version: '3.7'
services:
  #Monitor
  gatus:
    image: twinproduction/gatus:latest
    ports:
      - 80:8080
    volumes:
      - $PWD/gatus-gatus-config.yaml:/config/gatus-config.yaml

  # Caddy Proxy
  caddy:
    env_file: .env
    image: caddy:latest
    restart: unless-stopped
    ports:
      - 443:443
      - 443:443/udp
    volumes:
    - $PWD/Caddyfile:/etc/caddy/Caddyfile
    - caddy_data:/data
    - caddy_config:/config
    networks:
      - web
      - internal
volumes:
  caddy_data:
  caddy_config:

networks:
  web:
    external: false
  internal:
    external: false
    driver: bridge


