version: '3.7'
volumes:
  caddy_data:
  caddy_config:

networks:
  web:
    external: false
  internal:
    external: false
    driver: bridge
services:
  #Monitor
  gatus:
    image: twinproduction/gatus:latest
    ports:
      - 80:8080
    volumes:
      - $PWD/gatus-config.yaml:/config/gatus-config.yaml

  # Caddy Proxy
  caddy:
    env_file: .env
    image: caddy:latest
    restart: unless-stopped
    ports:
      - 443:443
      - 443:443/udp
    volumes:
    - $PWD/Caddyfile:/etc/caddy/Caddyfile
    - caddy_data:/data
    - caddy_config:/config
    networks:
      - web
      - internal

  api:
    env_file: .env
    image: fedi_api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONPATH="${PYTHONPATH}:/fedi_gatus/api_server"
    entrypoint: [ "python3", "fedi_gatus/api_server/__main__.py" ]
    ports:
      - "0.0.0.0:8080:8080"

  config:
    env_file: .env
    image: fedi_api
    environment:
      - PYTHONPATH="${PYTHONPATH}:/fedi_gatus"
    volumes:
      - $PWD/gatus-config.yaml:/app/gatus-config.yaml
    entrypoint: [ "python3", "fedi_gatus/config_gen" ]

  updater:
    env_file: .env
    image: fedi_api
    environment:
      - PYTHONPATH="${PYTHONPATH}:/fedi_gatus"
    entrypoint: [ "python3", "fedi_gatus/updater" ]
