version: '3.7'
volumes:
  caddy_data:
  caddy_config:

networks:
  web:
    external: false
  internal:
    external: false
    driver: bridge
services:
  #Monitor
  gatus:
    image: twinproduction/gatus:latest
    ports:
      - 80:8080
    volumes:
      - $PWD/gatus-gatus-config.yaml:/config/gatus-config.yaml

  # Caddy Proxy
  caddy:
    env_file: .env
    image: caddy:latest
    restart: unless-stopped
    ports:
      - 443:443
      - 443:443/udp
    volumes:
    - $PWD/Caddyfile:/etc/caddy/Caddyfile
    - caddy_data:/data
    - caddy_config:/config
    networks:
      - web
      - internal

  fedi_api:
    env_file: .env
#    restart: on-failure
    image: fedi_api
    environment:
      - PYTHONPATH="${PYTHONPATH}:/fedi_gatus"
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: [ "python3", "fedi_api/api.py" ]

    ports:
      - "0.0.0.0:8080:8080"
