version: '3.7'
volumes:
  caddy_data:
  caddy_config:
  gatus_config:
    external: false
  gatus_data:

services:
  #Monitor
  gatus:
    depends_on:
      - config
      - gatus_db
    image: twinproduction/gatus:latest
    ports:
      - 8888:8080
    volumes:
      - gatus_config:/config

  # Caddy Proxy
  caddy:
    env_file: .env
    image: caddy:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
    - $PWD/Caddyfile:/etc/caddy/Caddyfile
    - caddy_data:/data
    - caddy_config:/config

  api:
    env_file: .env
    image: fedi_api
    entrypoint: [ "python3", "fedi_gatus/api_server/__main__.py" ]
    ports:
      - "0.0.0.0:8080:8080"

  config:
    depends_on:
      - gatus_db
    env_file: .env
    image: fedi_api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - gatus_config:/app/fedi_gatus/config_gen/config
    entrypoint: [ "python3", "fedi_gatus/config_gen" ]

  gatus_db:
    hostname: gatusdb
    image: postgres
    env_file: .env
    volumes:
      - gatus_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"

#  updater:
#    env_file: .env
#    image: fedi_updater
#    build:
#      context: .
#      dockerfile: Dockerfile
#    entrypoint: [ "python3", "fedi_gatus/updater" ]

